server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/ms-pedido
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.error.include-message=always

spring.rabbitmq.addresses=amqps://rwsettgl:JJhoRVRRgTRw1I-9rfL9_MNTbfWvC66-@fuji.lmq.cloudamqp.com/rwsettgl
broker.queue.processamento.name=exchange.processamento



# Mostra os valores que você está tentando salvar
logging.level.org.hibernate.orm.jdbc.bind=trace

# Inicialização do Schema (Se você estiver usando Spring Session)
spring.session.jdbc.initialize-schema=always


# Diminui a verbosidade do log para erros de stack trace
logging.level.org.springframework.web=ERROR
# Mostra apenas o essencial no console
server.error.include-stacktrace=never
spring.jpa.properties.hibernate.format_sql=true
